version: '3'

services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
  db:
    image: mariadb:10.4
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 63jWSKKwiH
      MYSQL_DATABASE: forex
      MYSQL_USER: forex_app
      MYSQL_PASSWORD: super_secret_password

